### ISSUE TITLE
vendor.js not compiling

### ISSUE THREAD

**Issue by ericlbarnes** [monokrome/brunch-with-grits#4]
I just created a new brunch project with this as I hoped it would be a good starting point for integrating with bower. 

After installing and running `brunch build` and/or `brunch watch --server` it seems the vendor.js is never built. 

Since I am brand new to brunch I have no idea why this wouldn't be working but wanted to file an issue in case it is a bug or in case I am missing something obvious.

**Comment by monokrome** [comment]
Just a heads up, I'm looking into this now.

Did you run `bower install`?

**Comment by ericlbarnes** [comment]
Yeah - http://d.pr/i/kxO6

**Comment by ericlbarnes** [comment]
I think this may be it: 

```
› brunch -v
1.6.3
```

I upgraded but now build will not seem to run. Looks like it is on my end. :smile:

**Comment by ericlbarnes** [comment]
Runs perfect now. Everything I had was old. :-1: 

In case anyone else ever comes across this I had node v0.8.6 and grunt 1.6. Upgrading both resolved the issues. 

Reference: https://github.com/brunch/brunch/issues/666

**Comment by monokrome** [comment]
Happy that you found it out. Let me know if you run in to any other problems.
